cluster.name: "smapp-elastic"
node.name: ${HOSTNAME}
network.host: 0.0.0.0
discovery.zen.ping.unicast.hosts: ["192.168.0.71:9300", "192.168.0.81:9300", "192.168.0.102:9300"]
discovery.zen.minimum_master_nodes: 2
node.master: true
node.data: true
