version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    command: >
        elasticsearch
        --node.name=$HOSTNAME
        --cluster.name="smapp-elastic"
        --network.host=0.0.0.0
        --discovery.zen.ping.multicast.enabled=false
        --discovery.zen.minimum_master_nodes=2
        --discovery.zen.ping.unicast.hosts="192.168.0.71,192.168.0.81,192.168.0.102"
        --node.master=true
        --node.data=true
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: zen
      ES_JAVA_OPTS: "-Xmx16000m -Xms16000m"
    networks:
      - elk

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
